org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.caching=true

# Mod properties
mod.version=1.4.0
mod.group=com.evandev.treeliable
mod.id=treeliable
mod.name=Treeliable
mod.author=Evan
mod.credits=
mod.license=MIT
mod.description=A simple, no-nonsense tree chopping mod.
publish.modrinth=FllppLY0
publish.curseforge=1502764

# Mod setup
deps.neoforge_loader_version_range=[4,)
deps.forge_loader_version_range=[47,)

# Loom
loomx.loom_version=1.18.2
